TheWeddingOf.Web/Controllers/RsvpController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheWeddingOf.Models;
using TheWeddingOf.Services;

namespace TheWeddingOf.Web.Controllers
{
    public class RsvpController : Controller
    {
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RsvpService(userId);
            var model = service.GetRsvps();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RsvpCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RsvpService(userId);
            service.CreateRsvp(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var service = CreateRsvpService();
            var detail = service.GetRsvpById(id);
            var model =
                new RsvpEdit
                {
                    Names = detail.Names,
                    RsvpId = detail.RsvpId,
                    FoodOne = detail.FoodOne,
                    FoodTwo = detail.FoodTwo,
                    YayOrNay = detail.YayOrNay,
                    Comments = detail.Comments
                };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, RsvpEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.RsvpId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateRsvpService();

            if (service.UpdateRsvp(model))
            {
                TempData["SaveResult"] = "Your RSVP was sent";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your RSVP Could not be sent.");
            return View();
        }

        private RsvpService CreateRsvpService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RsvpService(userId);
            return service;
        }
    }
}

TheWeddingOf.Web/Views/Rsvp/Create.cshtml
@model TheWeddingOf.Models.RsvpCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RsvpCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Names, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Names, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Names, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodTwo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodTwo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FoodTwo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodOne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodOne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FoodOne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YayOrNay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.YayOrNay)
                    @Html.ValidationMessageFor(model => model.YayOrNay, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TheWeddingOf.Web/Views/Rsvp/Edit.cshtml
@model TheWeddingOf.Models.RsvpEdit

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    
    <br />
    <div class="form-horizontal text-center card shadow-lg ml-auto mr-auto" style="width:70%">
        <br />
        <h3>RSVP</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RsvpId)

        <div class="form-group">
            <div class="">
                <strong>@Html.DisplayFor(model => model.Names, new { @class = "control-label col-md-2 mr-auto ml-auto" })</strong>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YayOrNay, htmlAttributes: new { @class = "control-label col-md-2 mr-auto ml-auto" })
            <div class="">
                <div class="">
                    <label>✓</label>
                    @Html.RadioButtonFor(model => model.YayOrNay, true)
                    
                    <label>✗</label>
                    @Html.RadioButtonFor(model => model.YayOrNay, false)
                    @Html.ValidationMessageFor(model => model.YayOrNay, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodOne, htmlAttributes: new { @class = "control-label col-md-2 mr-auto ml-auto" })
            <div>
                <label>Chicken</label>
                @Html.RadioButtonFor(model => model.FoodOne, 1, new { @name = "foodOptions" })
                <br />
                <label>Tortellini</label>
                @Html.RadioButtonFor(model => model.FoodOne, 2, new { @name = "foodOptions" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control ml-auto mr-auto" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Send" class="btn" style="background-color:#800020; color:white; text-decoration:none;" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-light" })
        </div>
        <br />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TheWeddingOf.Web/Views/Rsvp/Index.cshtml
@model IEnumerable<TheWeddingOf.Models.RsvpListItem>

@{
    ViewBag.Title = "Index";
}

<p>
    @if (User.Identity.Name == "gjosephw24@gmail.com")
    {
        @Html.ActionLink("Create New", "Create")
    }
</p>

<div class="card text-center shadow-lg mr-auto ml-auto" style="width: 70%;">
    <br />
    <h2>RSVP</h2>
    <p>Find your name on the list and click RSVP!</p>
    <p>Press control+f on windows or command+f on mac to search for your name easier!</p>
    <br />
    <table class="table">

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <strong>@Html.DisplayFor(modelItem => item.Names)</strong>
                </td>
                <td>
                    <a style="background-color:#800020; color:white; text-decoration:none;" class="btn shadow-lg" href="@Url.Action("Edit", "Rsvp", new { id = item.RsvpId })">RSVP &raquo;</a>
                </td>
            </tr>
        }
    </table>
</div>